#!/usr/bin/env python3
#
#This my code for my calendar with "Monday" in it
#


  def main(): 
        Mycalendar1 =  Day: Monday     Subject   Time
                                       
                                       ELA       9:10 - 10:15
                                       BREAK     10:15 - 10:35
                                       SS        10:35 - 11:40
                                       LUNCH     11:40 - 12:10
                                       PF        12:10 - 1:15
                       
                       #This is my schedule
                       print "My schedule"
                       
